// <auto-generated />
namespace AcquireLunch.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddPersonIdToSingleOrderFixAgain : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddPersonIdToSingleOrderFixAgain));
        
        string IMigrationMetadata.Id
        {
            get { return "201211091023078_AddPersonIdToSingleOrderFixAgain"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
