// <auto-generated />
namespace AcquireLunch.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class PeopleAndOrders : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PeopleAndOrders));
        
        string IMigrationMetadata.Id
        {
            get { return "201211091006487_PeopleAndOrders"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
